CREATE TABLE public.team
(
    id    int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    color varchar NULL DEFAULT 'RED'::character varying,
    CONSTRAINT team_pkey PRIMARY KEY (id)
);

CREATE TABLE public.game_user
(
    id         int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    "level"    int8        NULL     DEFAULT 1,
    coins      int8        NULL     DEFAULT 0,
    username   varchar     NOT NULL DEFAULT 'Гость'::character varying,
    team_id    int8        NULL,
    city       varchar(23) NULL     DEFAULT 'Екатеринбург'::character varying,
    "password" varchar     NOT NULL,
    "role"     varchar     NOT NULL,
    email      varchar     NOT NULL,
    CONSTRAINT game_user_pkey PRIMARY KEY (id),
    CONSTRAINT game_user_un UNIQUE (email)
);

CREATE TABLE public.game_chunk
(
    id      varchar NOT NULL,
    "owner" int8    NULL,
    CONSTRAINT game_chunk_pk PRIMARY KEY (id)
);
ALTER TABLE public.game_chunk
    ADD CONSTRAINT game_chunk_owner_fkey FOREIGN KEY (owner) REFERENCES public.game_user (id);

CREATE TABLE public.skill
(
    id           int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    "name"       varchar NULL,
    max_level    int4    NULL DEFAULT 1,
    description  varchar NULL DEFAULT ''::character varying,
    upgrade_cost int4    NULL DEFAULT 0,
    image_name   varchar NULL DEFAULT ''::character varying,
    CONSTRAINT skill_pkey PRIMARY KEY (id)
);

CREATE TABLE public.user_skills
(
    user_id       int4 NOT NULL,
    skill_id      int4 NOT NULL,
    current_level int4 NULL DEFAULT 1,
    CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id)
);
ALTER TABLE public.user_skills
    ADD CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skill (id);
ALTER TABLE public.user_skills
    ADD CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.game_user (id);

CREATE TABLE public.user_friends
(
    user_id   int4 NOT NULL,
    friend_id int4 NOT NULL,
    CONSTRAINT user_friends_pkey PRIMARY KEY (user_id, friend_id)
);
ALTER TABLE public.user_friends
    ADD CONSTRAINT user_friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.game_user (id);
ALTER TABLE public.user_friends
    ADD CONSTRAINT user_friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.game_user (id);

CREATE TABLE public.sessions
(
    uuid      uuid      NOT NULL,
    user_id   int8      NOT NULL,
    ip        inet      NULL,
    created   timestamp NOT NULL,
    refreshed timestamp NOT NULL,
    expires   timestamp NOT NULL,
    useragent varchar   NULL,
    CONSTRAINT sessions_pk PRIMARY KEY (uuid)
);