CREATE TABLE team
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color varchar DEFAULT 'RED'
);

CREATE TABLE game_user
(
    id       int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level    int8         DEFAULT 1,
    coins    int8         DEFAULT 0,
    username varchar     DEFAULT 'Гость',
    password varchar,
    email    varchar,
    team_id  int8 REFERENCES team (id),
    city     varchar(23) DEFAULT 'Екатеринбург'
);

CREATE TABLE game_chunk
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner int8 REFERENCES game_user (id)
);

CREATE TABLE skill
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar,
    max_level    int8     DEFAULT 1,
    description  varchar DEFAULT '',
    upgrade_cost int8     DEFAULT 0,
    image_name   varchar DEFAULT ''
);

CREATE TABLE user_skills
(
    user_id       int8 REFERENCES game_user (id),
    skill_id      int8 REFERENCES skill (id),
    current_level int8 DEFAULT 1,
    PRIMARY KEY (user_id, skill_id)
);

CREATE TABLE user_friends
(
    user_id   int8 REFERENCES game_user (id),
    friend_id int8 REFERENCES game_user (id),
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE public.sessions
(
    uuid uuid NOT NULL,
    user_id int8 NOT NULL,
    ip inet NULL,
    created timestamp NOT NULL,
    refreshed timestamp NOT NULL,
    expires timestamp NOT NULL,
    useragent varchar NULL,
    CONSTRAINT sessions_pk PRIMARY KEY (uuid)
);