CREATE TABLE team
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color varchar DEFAULT 'RED'
);

CREATE TABLE game_user
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level    int         DEFAULT 1,
    coins    int         DEFAULT 0,
    nickname varchar     DEFAULT 'Гость',
    team_id  int REFERENCES team (id),
    city     varchar(23) DEFAULT 'Екатеринбург'
);

CREATE TABLE game_chunk
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner int REFERENCES game_user (id)
);

CREATE TABLE skill
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar,
    max_level    int     DEFAULT 1,
    description  varchar DEFAULT '',
    upgrade_cost int     DEFAULT 0,
    image_name   varchar DEFAULT ''
);

CREATE TABLE user_skills
(
    user_id       int REFERENCES game_user (id),
    skill_id      int REFERENCES skill (id),
    current_level int DEFAULT 1,
    PRIMARY KEY (user_id, skill_id)
);

CREATE TABLE user_friends
(
    user_id   int REFERENCES game_user (id),
    friend_id int REFERENCES game_user (id),
    PRIMARY KEY (user_id, friend_id)
);