CREATE TABLE public.team
(
    id    int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    color varchar NULL DEFAULT 'RED'::character varying,
    CONSTRAINT team_pkey PRIMARY KEY (id)
);

CREATE TABLE public.game_user (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    "level" int8 NULL DEFAULT 1,
    coins int8 NULL DEFAULT 0,
    username varchar NOT NULL DEFAULT 'Гость'::character varying,
    avatar varchar NOT NULL DEFAULT '1'::character varying,
    team_id int8 NULL,
    city varchar(23) NULL DEFAULT 'Екатеринбург'::character varying,
    "password" varchar NOT NULL,
    "role" varchar NOT NULL,
    email varchar NOT NULL,
    verified bool NOT NULL DEFAULT false,
    CONSTRAINT game_user_pkey PRIMARY KEY (id),
    CONSTRAINT game_user_un UNIQUE (email),
    CONSTRAINT game_user_un1 UNIQUE (username)
);
ALTER TABLE public.game_user ADD CONSTRAINT game_user_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.team(id);

CREATE TABLE public.game_chunk
(
    id      varchar NOT NULL,
    "owner" int8    NULL,
    CONSTRAINT game_chunk_pk PRIMARY KEY (id)
);
ALTER TABLE public.game_chunk ADD CONSTRAINT game_chunk_owner_fkey FOREIGN KEY (owner) REFERENCES public.game_user (id);

CREATE TABLE public."cost" (
    id int8 NOT NULL,
    cost_value json NOT NULL,
    CONSTRAINT cost_pk PRIMARY KEY (id)
);

CREATE TABLE public."rule" (
    id int8 NOT NULL,
    rule_value json NOT NULL,
    CONSTRAINT rule_pk PRIMARY KEY (id)
);

CREATE TABLE public.skill (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    "name" varchar NULL,
    max_level int4 NULL DEFAULT 1,
    description varchar NULL DEFAULT ''::character varying,
    image_name varchar NULL DEFAULT ''::character varying,
    icon varchar NULL DEFAULT ''::character varying,
    rule_id int8 NOT NULL,
    cost_id int8 NOT NULL,
    CONSTRAINT skill_pkey PRIMARY KEY (id)
);
ALTER TABLE public.skill ADD CONSTRAINT skill_fk FOREIGN KEY (rule_id) REFERENCES public."rule"(id);
ALTER TABLE public.skill ADD CONSTRAINT skill_fk_1 FOREIGN KEY (cost_id) REFERENCES public."cost"(id);

CREATE TABLE public.user_skills
(
    user_id       int4 NOT NULL,
    skill_id      int4 NOT NULL,
    current_level int4 NULL DEFAULT 1,
    CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id)
);
ALTER TABLE public.user_skills
    ADD CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skill (id);
ALTER TABLE public.user_skills
    ADD CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.game_user (id);

CREATE TABLE public.user_friends
(
    user_id   int4 NOT NULL,
    friend_id int4 NOT NULL,
    CONSTRAINT user_friends_pkey PRIMARY KEY (user_id, friend_id)
);
ALTER TABLE public.user_friends
    ADD CONSTRAINT user_friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.game_user (id);
ALTER TABLE public.user_friends
    ADD CONSTRAINT user_friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.game_user (id);

CREATE TABLE public.user_followers
(
    user_id   int4 NOT NULL,
    follower_id int4 NOT NULL,
    CONSTRAINT user_followers_pkey PRIMARY KEY (user_id, follower_id)
);
ALTER TABLE public.user_followers
    ADD CONSTRAINT user_followers_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.game_user (id);
ALTER TABLE public.user_followers
    ADD CONSTRAINT user_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.game_user (id);

CREATE TABLE public.sessions (
    uuid uuid NOT NULL,
    user_id int8 NOT NULL,
    ip inet NULL,
    created timestamp NOT NULL,
    refreshed timestamp NOT NULL,
    expires timestamp NOT NULL,
    useragent varchar NULL,
    CONSTRAINT sessions_pk PRIMARY KEY (uuid)
);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_fk FOREIGN KEY (user_id) REFERENCES public.game_user(id);

CREATE TABLE public.verification_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT verification_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.verification_tokens ADD CONSTRAINT verification_tokens_fk FOREIGN KEY (user_id) REFERENCES public.game_user(id);

CREATE TABLE public.recovery_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT recovery_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.recovery_tokens ADD CONSTRAINT recovery_tokens_fk FOREIGN KEY (user_id) REFERENCES public.game_user(id);

CREATE TABLE public.event_providers (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    url varchar NULL,
    CONSTRAINT event_providers_pk PRIMARY KEY (id)
);

CREATE TABLE public.event_categories (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    CONSTRAINT event_categories_pk PRIMARY KEY (id)
);

CREATE TABLE public.map_events (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    provider_id int8 NOT NULL,
    "name" varchar NULL,
    starts_at timestamp NULL,
    ends_at timestamp NULL,
    url varchar NULL,
    verified bool NOT NULL DEFAULT false,
    CONSTRAINT map_events_pk PRIMARY KEY (id)
);
ALTER TABLE public.map_events ADD CONSTRAINT map_events_fk FOREIGN KEY (provider_id) REFERENCES public.event_providers(id);
ALTER TABLE public.map_events ADD CONSTRAINT map_events_u UNIQUE (url);

CREATE TABLE public.map_events_category (
    event_id int8 NOT NULL,
    category_id int8 NOT NULL,
    CONSTRAINT map_events_category_pk PRIMARY KEY (event_id,category_id)
);
ALTER TABLE public.map_events_category ADD CONSTRAINT map_events_category_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_category ADD CONSTRAINT map_events_category_category_fk FOREIGN KEY (category_id) REFERENCES public.event_categories(id);

CREATE TABLE public.map_events_game_chunk (
    event_id int8 NOT NULL,
    chunk_id varchar NOT NULL,
    CONSTRAINT map_events_game_chunk_pk PRIMARY KEY (event_id,chunk_id)
);
ALTER TABLE public.map_events_game_chunk ADD CONSTRAINT map_events_game_chunk_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_game_chunk ADD CONSTRAINT map_events_game_chunk_chunk_fk FOREIGN KEY (chunk_id) REFERENCES public.game_chunk(id);

CREATE TABLE public.map_events_game_user (
    event_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT map_events_game_user_pk PRIMARY KEY (event_id,user_id)
);
ALTER TABLE public.map_events_game_user ADD CONSTRAINT map_events_game_user_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_game_user ADD CONSTRAINT map_events_game_user_user_fk FOREIGN KEY (user_id) REFERENCES public.game_user(id);