CREATE TABLE public.teams
(
    id    int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    color varchar NULL DEFAULT 'RED'::character varying,
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rounds
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    name varchar(30) DEFAULT 'Раунд 1'::character varying,
    starts timestamp NOT NULL,
    ends timestamp NOT NULL,
    active boolean not null DEFAULT false,
    CONSTRAINT rounds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    name varchar(30) NOT NULL DEFAULT 'Yekaterinburg'::character varying,
    locale varchar(20) NOT NULL DEFAULT 'Asia/Yekaterinburg'::character varying,
    chunks json not null,
    CONSTRAINT cities_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX only_one_true_for_round ON public.rounds (active) WHERE (active);
CREATE TABLE public.users(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    "level" int8 NOT NULL DEFAULT 1,
    coins int8 NOT NULL DEFAULT 0,
    username varchar NOT NULL DEFAULT 'Гость'::character varying,
    avatar varchar NOT NULL DEFAULT 'guest.jpg'::character varying,
    "password" varchar NOT NULL,
    "role" varchar NOT NULL,
    email varchar NOT NULL,
    verified bool NOT NULL DEFAULT false,
    captured_chunks int8 not null DEFAULT 0,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    UNIQUE (email, username)
);
CREATE TABLE public.users_rounds_team_city
(
    user_id int8 NOT NULL,
    round_id int8 NOT NULL,
    team_id int8 NOT NULL,
    city_id int8 NOT NULL,
    CONSTRAINT users_rounds_team_pk PRIMARY KEY (user_id,round_id),
    UNIQUE (user_id,round_id)
);
ALTER TABLE public.users_rounds_team_city ADD CONSTRAINT urt_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities (id);
ALTER TABLE public.users_rounds_team_city ADD CONSTRAINT urt_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams (id);
ALTER TABLE public.users_rounds_team_city ADD CONSTRAINT urt_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds (id);
ALTER TABLE public.users_rounds_team_city ADD CONSTRAINT urt_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.chunks
(
    id      varchar NOT NULL,
    round_id int8 not null,
    city_id int8 not null,
    "owner" int8    NULL,
    CONSTRAINT chunks_pk PRIMARY KEY (id, round_id),
    UNIQUE (id,round_id, city_id)
);
ALTER TABLE public.chunks ADD CONSTRAINT chunks_owner_fkey FOREIGN KEY (owner) REFERENCES public.users (id);
ALTER TABLE public.chunks ADD CONSTRAINT chunks_round_fkey FOREIGN KEY (round_id) REFERENCES public.rounds (id);
ALTER TABLE public.chunks ADD CONSTRAINT chunks_city_fkey FOREIGN KEY (city_id) REFERENCES public.cities (id);

CREATE TABLE public.costs (
    id int8 NOT NULL,
    cost_value json NOT NULL,
    CONSTRAINT cost_pk PRIMARY KEY (id)
);

CREATE TABLE public.rules(
    id int8 NOT NULL,
    rule_value json NOT NULL,
    CONSTRAINT rule_pk PRIMARY KEY (id)
);

CREATE TABLE public.skills(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    "name" varchar NULL,
    max_level int4 NULL DEFAULT 1,
    description varchar NULL DEFAULT ''::character varying,
    image_name varchar NULL DEFAULT ''::character varying,
    icon varchar NULL DEFAULT ''::character varying,
    rule_id int8 NOT NULL,
    cost_id int8 NOT NULL,
    CONSTRAINT skill_pkey PRIMARY KEY (id)
);
ALTER TABLE public.skills ADD CONSTRAINT skill_fk FOREIGN KEY (rule_id) REFERENCES public.rules(id);
ALTER TABLE public.skills ADD CONSTRAINT skill_fk_1 FOREIGN KEY (cost_id) REFERENCES public.costs (id);

CREATE TABLE public.users_skills
(
    user_id       int8 NOT NULL,
    skill_id      int8 NOT NULL,
    current_level int4 NULL DEFAULT 1,
    CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id)
);
ALTER TABLE public.users_skills
    ADD CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills (id);
ALTER TABLE public.users_skills
    ADD CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.users_friends
(
    user_id   int8 NOT NULL,
    friend_id int8 NOT NULL,
    CONSTRAINT users_friends_pkey PRIMARY KEY (user_id, friend_id)
);
ALTER TABLE public.users_friends
    ADD CONSTRAINT users_friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.users (id);
ALTER TABLE public.users_friends
    ADD CONSTRAINT users_friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.users_followers
(
    user_id   int8 NOT NULL,
    follower_id int8 NOT NULL,
    CONSTRAINT users_followers_pkey PRIMARY KEY (user_id, follower_id)
);
ALTER TABLE public.users_followers
    ADD CONSTRAINT users_followers_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.users (id);
ALTER TABLE public.users_followers
    ADD CONSTRAINT users_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.sessions (
    uuid uuid NOT NULL,
    user_id int8 NOT NULL,
    ip inet NULL,
    created timestamp NOT NULL,
    refreshed timestamp NOT NULL,
    expires timestamp NOT NULL,
    useragent varchar NULL,
    CONSTRAINT sessions_pk PRIMARY KEY (uuid)
);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.verification_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT verification_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.verification_tokens ADD CONSTRAINT verification_tokens_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.recovery_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT recovery_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.recovery_tokens ADD CONSTRAINT recovery_tokens_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.event_providers (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    url varchar NULL,
    CONSTRAINT event_providers_pk PRIMARY KEY (id)
);

CREATE TABLE public.event_categories (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    CONSTRAINT event_categories_pk PRIMARY KEY (id)
);

CREATE TABLE public.map_events (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    provider_id int8 NOT NULL,
    "name" varchar NULL,
    starts_at timestamp NULL,
    ends_at timestamp NULL,
    url varchar NULL,
    verified bool NOT NULL DEFAULT false,
    ad bool NOT NULL DEFAULT false,
    CONSTRAINT map_events_pk PRIMARY KEY (id)
);
ALTER TABLE public.map_events ADD CONSTRAINT map_events_provider_fk FOREIGN KEY (provider_id) REFERENCES public.event_providers(id);
ALTER TABLE public.map_events ADD CONSTRAINT map_events_u UNIQUE (url);

CREATE TABLE public.map_events_categories (
    event_id int8 NOT NULL,
    category_id int8 NOT NULL,
    CONSTRAINT map_events_categories_pk PRIMARY KEY (event_id,category_id)
);
ALTER TABLE public.map_events_categories ADD CONSTRAINT map_events_category_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_categories ADD CONSTRAINT map_events_category_category_fk FOREIGN KEY (category_id) REFERENCES public.event_categories(id);

CREATE TABLE public.map_events_chunks(
    event_id int8 NOT NULL,
    round_id int8 not null,
    city_id int8 not null,
    chunk_id varchar NOT NULL,
    CONSTRAINT map_events_chunks_pk PRIMARY KEY (event_id,chunk_id)
);
ALTER TABLE public.map_events_chunks ADD CONSTRAINT map_events_game_chunk_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_chunks ADD CONSTRAINT map_events_game_chunk_chunk_fk FOREIGN KEY (chunk_id,round_id, city_id) REFERENCES public.chunks (id,round_id, city_id);

CREATE TABLE public.map_events_users (
    event_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT map_events_users_pk PRIMARY KEY (event_id,user_id)
);
ALTER TABLE public.map_events_users ADD CONSTRAINT map_events_game_user_event_fk FOREIGN KEY (event_id) REFERENCES public.map_events(id);
ALTER TABLE public.map_events_users ADD CONSTRAINT map_events_game_user_user_fk FOREIGN KEY (user_id) REFERENCES public.users (id);