---- SETTINGS OF GAME
CREATE schema settings;
CREATE TABLE settings.game(
    id int8 not null,
    chunk_reward int4 not null default 1,
    team_change_cost int4 not null default 100,
    CONSTRAINT game_settings_pk PRIMARY KEY (id)
);
CREATE TABLE settings.costs (
    id int8 NOT NULL,
    cost_value json NOT NULL,
    CONSTRAINT cost_pk PRIMARY KEY (id)
);
CREATE TABLE settings.rules(
    id int8 NOT NULL,
    rule_value json NOT NULL,
    CONSTRAINT rule_pk PRIMARY KEY (id)
);

----
CREATE TYPE public.oauth_providers_enum AS ENUM (
    'VK',
    'GOOGLE'
);
CREATE TABLE public.images(
    uuid uuid not null,
    url varchar unique not null,
    file varchar unique null,
    is_default boolean not null default false,
    CONSTRAINT images_pkey PRIMARY KEY (uuid)
);
CREATE TABLE public.teams(
    id    int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    color varchar NULL DEFAULT 'RED'::character varying,
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rounds(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    name varchar(30) DEFAULT 'Раунд 1'::character varying,
    starts timestamp NOT NULL,
    ends timestamp NOT NULL,
    active boolean not null DEFAULT false,
    game_settings_id int8 not null,
    CONSTRAINT rounds_pkey PRIMARY KEY (id),
    CONSTRAINT round_game_settings foreign key (game_settings_id) references settings.game(id)
);
CREATE TABLE public.cities(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    name varchar(30) NOT NULL DEFAULT 'Yekaterinburg'::character varying,
    locale varchar(20) NOT NULL DEFAULT 'Asia/Yekaterinburg'::character varying,
    chunks_resolution int4 not null default 6,
    chunks json not null,
    CONSTRAINT cities_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX only_one_true_for_round ON public.rounds (active) WHERE (active);
CREATE TABLE public.users(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    "level" int8 NOT NULL DEFAULT 0,
    coins int8 NOT NULL DEFAULT 0,
    username varchar NOT NULL,
    avatar_uuid uuid NOT NULL DEFAULT 'b3feae74-7915-4ed8-9965-419b9a0a6283'::uuid,
    "password" varchar NOT NULL,
    "role" varchar NOT NULL,
    email varchar NOT NULL,
    verified bool NOT NULL DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_images_fkey FOREIGN KEY (avatar_uuid) references public.images(uuid),
    UNIQUE (email, username)
);
CREATE TABLE public.users_oauth(
    user_id int8 not null,
    oauth_id varchar not null,
    oauth_provider public.oauth_providers_enum not null,
    CONSTRAINT users_oauth_pkey PRIMARY KEY (user_id, oauth_provider),
    unique (user_id, oauth_provider)
);
CREATE TABLE public.users_rounds_team_city(
    user_id int8 NOT NULL,
    round_id int8 NOT NULL,
    team_id int8 NOT NULL,
    city_id int8 NOT NULL,
    captured_chunks int8 not null DEFAULT 0,
    CONSTRAINT users_rounds_team_pk PRIMARY KEY (user_id,round_id,city_id),
    CONSTRAINT urt_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities (id),
    CONSTRAINT urt_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams (id),
    CONSTRAINT urt_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds (id),
    CONSTRAINT urt_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id),
    UNIQUE (user_id,round_id,city_id)
);
CREATE TABLE public.chunks
(
    id      varchar NOT NULL,
    round_id int8 not null,
    city_id int8 not null,
    "owner" int8    NULL,
    CONSTRAINT chunks_pk PRIMARY KEY (id, round_id),
    UNIQUE (id,round_id, city_id),
    CONSTRAINT chunks_owner_fkey FOREIGN KEY (owner,round_id,city_id) REFERENCES public.users_rounds_team_city(user_id,round_id,city_id)
);
CREATE TABLE public.skills(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    "name" varchar NULL,
    max_level int4 NULL DEFAULT 1,
    description varchar NULL DEFAULT ''::character varying,
    image_uuid uuid not null default '2da609a9-f54a-4c64-bf8d-88e38cdbc541'::uuid,
    icon_uuid  uuid not null default 'aba1bbbe-af69-4da6-83ce-572546e2f37e'::uuid,
    rule_id int8 NOT NULL,
    cost_id int8 NOT NULL,
    CONSTRAINT skills_pkey PRIMARY KEY (id),
    CONSTRAINT skills_images_image_fkey FOREIGN KEY (image_uuid) references public.images(uuid),
    CONSTRAINT skills_images_icon_fkey FOREIGN KEY (icon_uuid) references public.images(uuid),
    CONSTRAINT skill_fk FOREIGN KEY (rule_id) REFERENCES settings.rules(id),
    CONSTRAINT skill_fk_1 FOREIGN KEY (cost_id) REFERENCES settings.costs (id)
);
CREATE TABLE public.users_skills
(
    user_id       int8 NOT NULL,
    skill_id      int8 NOT NULL,
    current_level int4 NULL DEFAULT 1,
    CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id),
    CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills (id),
    CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id)
);
CREATE TABLE public.users_friends
(
    user_id   int8 NOT NULL,
    friend_id int8 NOT NULL,
    CONSTRAINT users_friends_pkey PRIMARY KEY (user_id, friend_id),
    CONSTRAINT users_friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.users (id),
    CONSTRAINT users_friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id)
);
CREATE TABLE public.users_followers
(
    user_id   int8 NOT NULL,
    follower_id int8 NOT NULL,
    CONSTRAINT users_followers_pkey PRIMARY KEY (user_id, follower_id),
    CONSTRAINT users_followers_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.users (id),
    CONSTRAINT users_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id)
);
CREATE TABLE public.sessions (
    uuid uuid NOT NULL,
    user_id int8 NOT NULL,
    ip inet NULL,
    created timestamp NOT NULL,
    refreshed timestamp NOT NULL,
    expires timestamp NOT NULL,
    useragent varchar NULL,
    CONSTRAINT sessions_pk PRIMARY KEY (uuid)
);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.verification_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT verification_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.verification_tokens ADD CONSTRAINT verification_tokens_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE TABLE public.recovery_tokens (
    user_id int8 NOT NULL,
    "token" varchar NOT NULL,
    created timestamp NOT NULL,
    expires timestamp NOT NULL,
    CONSTRAINT recovery_tokens_pk PRIMARY KEY (user_id)
);
ALTER TABLE public.recovery_tokens ADD CONSTRAINT recovery_tokens_fk FOREIGN KEY (user_id) REFERENCES public.users (id);

---- MAP EVENTS
CREATE schema map_events;
CREATE TABLE map_events.providers (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    url varchar NULL,
    CONSTRAINT event_providers_pk PRIMARY KEY (id)
);
CREATE TABLE map_events.categories (
    id int8 NOT NULL,
    "name" varchar NOT NULL,
    CONSTRAINT event_categories_pk PRIMARY KEY (id)
);

CREATE TABLE map_events.events (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    provider_id int8 NOT NULL,
    "name" varchar NULL,
    description varchar NULL,
    starts_at timestamp NULL,
    ends_at timestamp NULL,
    url varchar NULL,
    verified bool NOT NULL DEFAULT false,
    active bool NOT NULL DEFAULT false,
    image_uuid uuid not null DEFAULT 'aad50520-1509-4a34-925e-72bc182189e2'::uuid,
    ad bool NOT NULL DEFAULT false,
    reward int4 not null default 0,
    CONSTRAINT map_events_pk PRIMARY KEY (id),
    CONSTRAINT map_events_images_fkey FOREIGN KEY (image_uuid) references public.images(uuid),
    CONSTRAINT map_events_provider_fk FOREIGN KEY (provider_id) REFERENCES map_events.providers(id),
    UNIQUE (url)
);

CREATE TABLE map_events.events_categories (
    event_id int8 NOT NULL,
    category_id int8 NOT NULL,
    CONSTRAINT map_events_categories_pk PRIMARY KEY (event_id,category_id),
    CONSTRAINT map_events_category_event_fk FOREIGN KEY (event_id) REFERENCES map_events.events(id),
    CONSTRAINT map_events_category_category_fk FOREIGN KEY (category_id) REFERENCES map_events.categories(id)
);
CREATE TABLE map_events.events_chunks(
    event_id int8 NOT NULL,
    round_id int8 not null,
    city_id int8 not null,
    chunk_id varchar NOT NULL,
    CONSTRAINT map_events_chunks_pk PRIMARY KEY (event_id,chunk_id),
    CONSTRAINT map_events_game_chunk_event_fk FOREIGN KEY (event_id) REFERENCES map_events.events(id),
    CONSTRAINT map_events_game_chunk_chunk_fk FOREIGN KEY (chunk_id,round_id,city_id) REFERENCES public.chunks (id,round_id,city_id)

);
CREATE TABLE map_events.events_users (
    event_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT map_events_users_pk PRIMARY KEY (event_id,user_id),
    CONSTRAINT map_events_game_user_event_fk FOREIGN KEY (event_id) REFERENCES map_events.events(id),
    CONSTRAINT map_events_game_user_user_fk FOREIGN KEY (user_id) REFERENCES public.users (id)
);